# Numpy Functions: Dot Product, Rounding Functions, Trigonometric Functions, matrix multiplications etc.

## Infinity and Nan

In [1]:
# 3/0 gives error

In [2]:
import numpy as np

In [3]:
np.array(3)/0

C:\Users\DELL\AppData\Local\Temp\ipykernel_3956\48870926.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array(3)/0


inf

In [7]:
a = np.inf     # Numpy has an object for infinity which gets called for infinity

In [8]:
a

inf

In [9]:
np.nan

nan

In [12]:
a = np.nan  # to store nan value

In [13]:
a

nan

## Dot Product

In [14]:
ara = np.array([1,2,3,44,5])
arb = np.array([3,4,5,6,7])

In [15]:
ara

array([ 1,  2,  3, 44,  5])

In [16]:
arb

array([3, 4, 5, 6, 7])

In [18]:
# dot product
ara.dot(arb)

325

In [20]:
# Transpose of a matrix - column will become row and vice versa
are = np.array([[1,2,3,4],[5,6,7,8]])
are

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
art = are.T

In [22]:
art

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#### min, max, mean, std values

In [23]:
ard = np.array([1,2,4,6,7,8,9,-12,-45,-110,556,342])

In [29]:
# min value
ard.min()

-110

In [30]:
# max value
ard.max()

556

In [26]:
ard.argmin()    # returns index of min value

9

In [27]:
ard.argmax()    # returns index of max value

10

In [31]:
# mean value
ard.mean()

64.0

In [33]:
# standard deviation value
ard.std()

180.61653671060503

In [36]:
# sorting array
ard.sort()

In [37]:
ard

array([-110,  -45,  -12,    1,    2,    4,    6,    7,    8,    9,  342,
        556])

## Rounding Function

In [38]:
ar = np.array([0.4,0.8,0.000035343,1.565677,3.5,88.97567463423,-1.54656778])

In [39]:
ar

array([ 4.00000000e-01,  8.00000000e-01,  3.53430000e-05,  1.56567700e+00,
        3.50000000e+00,  8.89756746e+01, -1.54656778e+00])

In [42]:
# rounding to 1st decimal place
ar.round(4)

array([ 0.4   ,  0.8   ,  0.    ,  1.5657,  3.5   , 88.9757, -1.5466])

In [41]:
# rounding a number
np.round(1.34546567687, 3)

1.345

In [43]:
# Floor: Rounding to nearest lower integer
np.floor(ar)

array([ 0.,  0.,  0.,  1.,  3., 88., -2.])

In [44]:
# Ceil: ceil() function rounds off decimal to nearest upper integer.
np.ceil(ar)

array([ 1.,  1.,  1.,  2.,  4., 89., -1.])

## Trigonometric Functions

In [47]:
ara    # values are taken in radian

array([ 1,  2,  3, 44,  5])

In [48]:
np.sin(ara)

array([ 0.84147098,  0.90929743,  0.14112001,  0.01770193, -0.95892427])

In [50]:
np.sin(np.pi/2)    # sin(pi/2) is 1

1.0

In [51]:
np.sin(0)

0.0

In [52]:
np.cos(0)

1.0

In [53]:
np.cos(np.pi/2)

6.123233995736766e-17

In [54]:
# converting to degrees
np.degrees(np.pi)

180.0

In [55]:
# inverse sin

np.degrees(np.arcsin(1))

90.0

In [56]:
# hypot function that takes the base and perpendicular values and produces hypotenuse

np.hypot(3,4)

5.0

## Logarithmic and Exponential Functions

In [59]:
np.exp(1)     # gives e^1

2.718281828459045

In [60]:
np.exp(2)

7.38905609893065

In [61]:
np.exp([1,2,4,6])

array([  2.71828183,   7.3890561 ,  54.59815003, 403.42879349])

In [62]:
# Natural log - log base e
np.log(1)

0.0

In [64]:
np.log(np.exp(1))      # log base e (e)

1.0

In [65]:
np.log10(10)         # log base 10 (10) 

1.0

In [66]:
np.log10(100)       # log base 10 (100)

2.0

In [68]:
np.log2(2)         # log base 2 (2)

1.0

# Matrix Multiplication : use @
- a*b : a is of m X n and b is of n X j, then product is of m X j

- condition for multiplication: no. columns of a and no. of rows of b should be equal 

In [69]:
ar = np.array([[2,3,4,5],[4,5,6,7]])

In [70]:
ar

array([[2, 3, 4, 5],
       [4, 5, 6, 7]])

In [71]:
art = np.array([[1,2],[4,5],[6,7],[8,9]])
art

array([[1, 2],
       [4, 5],
       [6, 7],
       [8, 9]])

In [72]:
# Matrix Multiplication

ar@art

array([[ 78,  92],
       [116, 138]])