# Dimensions in array

### 0-D array: Array having one element

In [1]:
import numpy as np

In [11]:
# 0-D array
arr = np.array(45)

# We can add only one element like this, adding more with comma will give error
# Use list or tuple for more than one element

In [12]:
# checking Dimension of array using ndim attribute
arr.ndim

# represents a single point in graph, that's why 0-D array

0

In [13]:
arr

array(45)

### 1-D array: Array having 0-D arrays as its elements
- Most common and basic arrays
- Similar to basic lists

In [14]:
arr = np.array([42,34,45])

# We can use either list or tuple

In [15]:
arr.ndim

1

In [16]:
arr

array([42, 34, 45])

### 2-D array: Array having 1-D arrays as its elements.
- Represents matrix or 2nd order tensor

In [17]:
arr = np.array([[1,2,3],[4,5,6]])

In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr.ndim

2

In [20]:
type(arr)

numpy.ndarray

In [21]:
# creating matrix using matrix function
mat = np.mat(np.array([[1,2,3],[4,5,6]]))

In [22]:
type(mat)

numpy.matrix

In [23]:
mat.ndim

2

In [24]:
# Matrix and 2-d Array are different

### 3-D array: 2-D arrays behave as element
- Represents 3rd order tensor

In [25]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[3,4,5]]])

In [27]:
arr.ndim

3

In [28]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [3, 4, 5]]])

### Higher Dimensional Arrays
- An array can have any number of dimensions
- ndmin argument

In [31]:
arr = np.array([1,2,3], ndmin = 5)

# ndmin is used to specify dimensions for our array

In [32]:
arr

array([[[[[1, 2, 3]]]]])

In [33]:
arr.ndim

5

### Shape: Checking Shape

In [34]:
arr = np.array([[1,2,3],[4,5,6]])

In [35]:
arr.shape

(2, 3)

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[3,4,5]]])

In [39]:
arr.shape

(2, 2, 3)

In [40]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [3, 4, 5]]])