## Using inbuilt methods for generating arrays

## Arange: Return an array with evenly spaced elements in the given elements in the given interval
- np.arange(start,stop,step)

In [2]:
import numpy as np

In [3]:
# make an array of pressures ranging from 0 to 5000 psi with a step size of 500 psi
pressures = np.arange(0,5500,500)

In [4]:
pressures

array([   0,  500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000])

In [5]:
pressures.ndim

1

## Linspace: Creates linearly spaced array
- Evenly spaced numbers over a specified interval
- Creating n datapoints between two points

In [7]:
# Create saturation array from 0 to 1 having 100 points

saturations = np.linspace(0,1,100)
saturations

# 0 and 1 both are present in our array
# this is 1-D array

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [8]:
saturations.shape

(100,)

## zeroes, ones and identity matrixes
- useful in reservoir simulation

In [14]:
# zeroes = place holder, useful in reservoir, placeholder for values of properties of reservoir
zero = np.zeros((50,50))
zero

# creates 50x50 array of zeros

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
# adding value 30 at (2,3)
zero[1][2] = 30

In [16]:
zero

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0., 30., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [20]:
# ones - matrix/array of 1s
p = np.ones((50,30))
p

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [18]:
# multiply by 500
pi = 500
p*pi

array([[500., 500., 500., ..., 500., 500., 500.],
       [500., 500., 500., ..., 500., 500., 500.],
       [500., 500., 500., ..., 500., 500., 500.],
       ...,
       [500., 500., 500., ..., 500., 500., 500.],
       [500., 500., 500., ..., 500., 500., 500.],
       [500., 500., 500., ..., 500., 500., 500.]])

In [21]:
# eye: Creates an identity matrix
i = np.eye(4)
i
# here we have to give only one input bcoz identity matrix is always square

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])