## Indexing for Higher dimensional Arrays

### Accessing elements

In [1]:
import numpy as np

In [2]:
#2d arrays
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[12,34,23]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [12, 34, 23]])

In [4]:
arr.ndim

2

In [5]:
arr.shape

(4, 3)

In [6]:
arr[1]

array([4, 5, 6])

In [7]:
arr[0]

array([1, 2, 3])

In [8]:
# accessing 5
arr[1][1]

5

In [9]:
# another way
arr[1,1]

5

In [10]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [12, 34, 23]])

In [11]:
arr[-2][-2]

8

In [12]:
arr[-2,-2]

8

In [13]:
# 3d Arrays
ar = np.array([[[1,2,3],[2,3,4]],[[34,45,56],[34,78,23]]])

In [14]:
ar

array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[34, 45, 56],
        [34, 78, 23]]])

In [15]:
ar[0]

array([[1, 2, 3],
       [2, 3, 4]])

In [16]:
ar[0][1]

array([2, 3, 4])

In [18]:
ar[0][1][1]

3

In [19]:
ar[0,1,1]

3

In [20]:
# High D array
arr = np.array([1,2,3,4,5,6],ndmin = 5)

In [21]:
arr

array([[[[[1, 2, 3, 4, 5, 6]]]]])

In [22]:
arr.ndim

5

In [23]:
arr[0][0][0][0]

array([1, 2, 3, 4, 5, 6])

In [24]:
arr[0][0][0][0][3]

4

In [25]:
arr[0,0,0,0,3]

4