# Random Number Generation

In [1]:
import numpy as np

# Generating totally random numbers:
- Doesn't follow any distributions

## Randint : Generating Random Integer
- provide the maximum number

In [10]:
np.random.randint(100)

35

In [13]:
np.random.randint(50,100)   # b/w 50 and 100

71

In [16]:
a = np.random.randint(250,350,(4,3))

# 4x3 matrix having random integers b/w 250 and 350

In [17]:
a

array([[285, 269, 326],
       [252, 303, 332],
       [257, 307, 349],
       [277, 342, 251]])

In [20]:
a = np.random.randint(250,350,(3,4,3))

# 3x4x3 matrix

In [21]:
a

array([[[268, 286, 287],
        [339, 326, 274],
        [339, 349, 335],
        [326, 338, 271]],

       [[303, 298, 292],
        [339, 322, 298],
        [312, 266, 297],
        [342, 322, 315]],

       [[327, 349, 332],
        [313, 264, 290],
        [332, 330, 252],
        [274, 293, 281]]])

## rand: Generating Random Float between 0 and 1
- provide size

In [23]:
np.random.rand()    

# no need to give any input
# will always give float value between 0 and 1

0.8669252048058305

In [25]:
np.random.rand(5)

# array of 5 elements having float value between 0 and 1

array([0.59505528, 0.41305074, 0.95343256, 0.33441741, 0.18431135])

In [27]:
np.random.rand(5,4)

# 5x4 2D matrix having float values between 0 and 1

array([[0.22442634, 0.59332648, 0.05789585, 0.82298636],
       [0.22787967, 0.12300244, 0.53747572, 0.47499338],
       [0.224924  , 0.3627122 , 0.25288761, 0.2367752 ],
       [0.30799368, 0.69523167, 0.18850315, 0.43495836],
       [0.0246998 , 0.70400677, 0.67691337, 0.32722616]])

In [29]:
np.random.rand(5,4,2)

# 5x4x2 3D matrix

array([[[0.41471047, 0.27702608],
        [0.6240463 , 0.08249822],
        [0.77664307, 0.17924809],
        [0.99894575, 0.59183995]],

       [[0.07839999, 0.99997752],
        [0.46871161, 0.82564675],
        [0.21308929, 0.11023871],
        [0.12750004, 0.78130027]],

       [[0.47369381, 0.11457363],
        [0.42011688, 0.89594668],
        [0.45342171, 0.43071871],
        [0.16537509, 0.45578946]],

       [[0.28097175, 0.59605938],
        [0.31057668, 0.2279801 ],
        [0.68817379, 0.72500311],
        [0.69532683, 0.05497864]],

       [[0.23343198, 0.03445205],
        [0.66506532, 0.37867758],
        [0.1057274 , 0.17645509],
        [0.69971936, 0.04936477]]])

In [30]:
# Creating matrix with floating number, not 0.24342

In [31]:
inte = np.random.randint(200,size = (3,4))

In [32]:
fl = np.random.rand(3,4)

In [34]:
inte + fl  # numbers are less than 200

array([[105.7609168 , 120.15698394, 199.98901205, 120.7799017 ],
       [143.68834695, 190.63596774, 163.21375632, 113.6960121 ],
       [164.00586329, 135.94055618, 132.4319863 ,   3.16646337]])

## Choice:
- generate a random value based on an array of values

In [41]:
np.random.choice([43,56,76,89])

# gives random value from given array

56

In [43]:
np.random.choice([43,56,76,89], size = (3,5))

# 3x5 2D array from given array

array([[56, 89, 56, 89, 76],
       [43, 43, 56, 56, 43],
       [43, 89, 89, 56, 76]])

## By using choice we can also specify probability for each value
- The sum of all probability numbers should be 1.

In [46]:
x = np.random.choice([3,5,7,9], p = [0.1,0.3,0.6,0.0], size = (5,6))

# sum of probabilities should be 1

In [47]:
x

array([[7, 7, 7, 7, 7, 7],
       [5, 5, 5, 5, 7, 7],
       [5, 7, 7, 5, 5, 7],
       [3, 7, 5, 7, 3, 7],
       [5, 3, 7, 7, 7, 7]])

In [48]:
y = np.random.choice([3,5,7,9], p = [1,0,0,0], size = (5,6))

In [49]:
y

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])